Node/teste/config/routes.rb
Teste::Application.routes.draw do
  resources :auctions

 	root :to => "auctions#index"

end

Node/teste/app/models/auction.rb
class Auction < ActiveRecord::Base
end

Node/teste/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Node/teste/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  # GET /auctions
  # GET /auctions.xml
  def index
    @auctions = Auction.all
    @auctions_ids = @auctions.map(&:id).join(',')
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @auctions }
    end
  end

  # GET /auctions/1
  # GET /auctions/1.xml
  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @auction }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.xml
  def new
    @auction = Auction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
  end

  # POST /auctions
  # POST /auctions.xml
  def create
    @auction = Auction.new(params[:auction])

    respond_to do |format|
      if @auction.save
        format.html { redirect_to(@auction, :notice => 'Auction was successfully created.') }
        format.xml  { render :xml => @auction, :status => :created, :location => @auction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @auction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.xml
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to(@auction, :notice => 'Auction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @auction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.xml
  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to(auctions_url) }
      format.xml  { head :ok }
    end
  end
end

Node/teste/app/helpers/application_helper.rb
module ApplicationHelper
end

Node/teste/app/helpers/auctions_helper.rb
module AuctionsHelper
end

Node/teste/app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :finish_at %><br />
    <%= f.datetime_select :finish_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Node/teste/app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

Node/teste/app/views/auctions/index.html.erb
<script src="http://127.0.0.1:8080/socket.io/socket.io.js" type="text/javascript"></script>
<script type="text/javascript">
	var objSocket = new io.Socket("127.0.0.1", {port: 8080});
	objSocket.connect();
	
	objSocket.on("connect", function(){
		console.warn("Bem vindo ao servidor");
	});
	
	objSocket.on("message", function(msg){
		var leilao = document.getElementById("auction_"+msg.id);
		leilao.innerHTML = msg.valor;
	});
	
	objSocket.on("disconnect", function(){
		console.warn("Você foi desconectado do servidor!");
		objSocket.disconnect();
	});
	
	function darlance(id){
		objSocket.send(id);
	}
	
	var ids = "<%= @auctions_ids %>".split(",");
	setInterval(function(){
		for(var i=0; i < ids.length; i++){
			elemento = document.getElementById("auction_tempo_"+ids[i]);
			elemento.innerHTML = parseInt(elemento.innerHTML) - 1;
		}
	}, 1000);
</script>
<h1>Listing auctions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th>Tempo restante</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @auctions.each do |auction| %>
  <tr>
    <td><%= auction.name %></td>
    <td id="auction_<%= auction.id %>"><%= auction.value %></td>
    <td><input onclick="javascript: darlance(<%= auction.id %>);" type="button" value="Dar lance!"></input></td>
    <td id="auction_tempo_<%= auction.id %>"><%= auction.finish_at.to_i - Time.now.to_i %></td>
    <td><%= link_to 'Show', auction %></td>
    <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
    <td><%= link_to 'Destroy', auction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Auction', new_auction_path %>

Node/teste/app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

Node/teste/app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @auction.name %>
</p>

<p>
  <b>Value:</b>
  <%= @auction.value %>
</p>


<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>

Node/teste/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>